return {
  {
    "nvimdev/dashboard-nvim",
    event = "VimEnter",
    config = function()
      require("dashboard").setup({
        theme = "doom",
        config = {
          header = {
            "",
            "",
            "",
            "▗▖ ▗▖▗▄▄▄▖▗▄▄▄▖▗▖ ▗▖▗▄▄▄ ▗▄▄▄▖▗▄▄▖▗▄▄▄▖▗▄▄▖  ▗▄▖ ▗▄▄▄▖",
            "▐▌ ▐▌  █  ▐▌   ▐▌ ▐▌▐▌  █▐▌   ▐▌ ▐▌ █  ▐▌ ▐▌▐▌ ▐▌  █  ",
            "▐▛▀▜▌  █  ▐▛▀▀▘▐▌ ▐▌▐▌  █▐▛▀▀▘▐▛▀▘  █  ▐▛▀▚▖▐▛▀▜▌  █  ",
            "▐▌ ▐▌▗▄█▄▖▐▙▄▄▖▝▚▄▞▘▐▙▄▄▀▐▙▄▄▖▐▌    █  ▐▌ ▐▌▐▌ ▐▌▗▄█▄▖",
            "",
            "",
            "",
            "",
          },
          center = {
            {
              icon = "    ",
              icon_hl = "Title",
              desc = "Find Files                  ",
              desc_hl = "String",
              key = "f",
              key_hl = "Number",
              key_format = " %s",
              action = "Telescope find_files",
            },
            {
              icon = "󰊢    ",
              icon_hl = "Title",
              desc = "Open Lazygit                ",
              desc_hl = "String",
              key = "g",
              key_hl = "Number",
              key_format = " %s",
              action = "LazyGit",
            },
            {
              icon = "    ",
              icon_hl = "Title",
              desc = "Open LazyVim                ",
              desc_hl = "String",
              key = "v",
              key_hl = "Number",
              key_format = " %s",
              action = "Lazy",
            },
            {
              icon = "    ",
              icon_hl = "Title",
              desc = "Goodbye, NeoVim!",
              desc_hl = "String",
              key = "q",
              key_hl = "Number",
              key_format = " %s",
              action = "qa",
            },
          },
          footer = {
            "",
            "",
            "",
            "   If at first you don't succeed, call it version 1.0",
            "",
            "",
            "    ☆  *    .      ☆    ",
            "      .∧＿∧  ∩    * ☆   ",
            "*  ☆ ( ・∀・)/ .        ",
            ".   ⊂       ノ* ☆       ",
            "☆ * (つ  ノ  .☆         ",
            "     (ノ                ",
          },
        },
      })
    end,
    dependencies = { { "nvim-tree/nvim-web-devicons" } },
  },
}
